In [ ]:
import numpy as np
import pandas as pd
import streamlit as st
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

: 

In [2]:
train_df=pd.read_csv('/content/train.csv')
test_df=pd.read_csv('/content/test.csv')
train_df=train_df[["OverallQual", "GrLivArea", "GarageArea", "YearBuilt","SalePrice"]]
test_df=test_df[["OverallQual", "GrLivArea", "GarageArea", "YearBuilt"]]

In [3]:
train_df.head()

OverallQual  GrLivArea  GarageArea  YearBuilt  SalePrice
0            7       1710         548       2003     208500
1            6       1262         460       1976     181500
2            7       1786         608       2001     223500
3            7       1717         642       1915     140000
4            8       2198         836       2000     250000

In [11]:
X_train = train_df.drop("SalePrice", axis = 1).to_numpy()
Y_train = train_df["SalePrice"].to_numpy()
X_test = test_df.to_numpy()
print("X_train", X_train)
print("Y_train", Y_train)

X_train [[   7 1710  548 2003]
 [   6 1262  460 1976]
 [   7 1786  608 2001]
 ...
 [   7 2340  252 1941]
 [   5 1078  240 1950]
 [   5 1256  276 1965]]
Y_train [208500 181500 223500 ... 266500 142125 147500]


In [14]:
X_train.shape

(1460, 4)

In [18]:
# Building Xbar
one = np.ones((X_train.shape[0], 1))
Xbar = np.concatenate((one, X_train), axis = 1)

# Calculating weights of the fitting line
A = np.dot(Xbar.T, Xbar)
b = np.dot(Xbar.T, Y_train)
w = np.dot(np.linalg.pinv(A), b)
print('w = ', w)


w =  [-8.23805261e+05  2.31109655e+04  5.57043800e+01  5.76036735e+01
  3.81532147e+02]


In [ ]:
# Dự đoán tập test
X_test = test_data[features]
y_preds_test = lr_model.predict(X_test)


# Huấn luyện Random Forest
rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(X_train, y_train)
y_preds_rf = rf_model.predict(X_test)